BEGIN TRANSACTION;
CREATE TABLE "MPStatus" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`groundSpeed`	REAL NOT NULL,
	`lat`	REAL NOT NULL,
	`lng`	REAL NOT NULL,
	`gpsstatus`	REAL NOT NULL,
	`satcount`	REAL NOT NULL,
	`roll`	REAL NOT NULL,
	`pitch`	REAL NOT NULL,
	`yaw`	REAL NOT NULL,
	`battery_voltage`	REAL NOT NULL,
	`battery_remaining`	INTEGER NOT NULL,
	`ax`	REAL NOT NULL,
	`ay`	REAL NOT NULL,
	`az`	REAL NOT NULL,
	`mx`	REAL NOT NULL,
	`my`	REAL NOT NULL,
	`mz`	REAL NOT NULL,
	`alt`	REAL NOT NULL DEFAULT 0.0,
	`timestamp`	TEXT NOT NULL
);
CREATE TABLE `MPMissions` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`status`	TEXT NOT NULL,
	`type`	TEXT NOT NULL,
	`commandSize`	INTEGER,
	`currentCommand`	INTEGER
);
CREATE TABLE "MPConfig" (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`HomeLat`	REAL NOT NULL,
	`HomeLng`	REAL NOT NULL,
	`AbortLat`	REAL NOT NULL,
	`AbortLng`	REAL NOT NULL,
	`Aborted`	INTEGER NOT NULL DEFAULT 0
);
INSERT INTO `MPConfig` VALUES (1,35.490163,24.064234,35.4904681,24.0648222,0);
CREATE TABLE `MPCommands` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`missionID`	INTEGER NOT NULL,
	`command`	TEXT NOT NULL,
	`sequence`	INTEGER NOT NULL,
	`latitude`	TEXT NOT NULL,
	`longitude`	TEXT NOT NULL,
	`speed`	INTEGER NOT NULL,
	`radius`	INTEGER NOT NULL
);
COMMIT;
